version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: resident-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: resident_management
      MYSQL_USER: resident_user
      MYSQL_PASSWORD: resident_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - resident-dev-network

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: resident-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://dung:tiendungpro123@cdr.cc3cumaiaj7q.us-east-1.rds.amazonaws.com:3306/resident_management
      JWT_SECRET: your-super-secret-jwt-key-here
      JWT_EXPIRES_IN: 7d
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - resident-dev-network
    command: npm run start:dev

  # Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: resident-frontend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - resident-dev-network
    command: npm run dev

volumes:
  mysql_dev_data:

networks:
  resident-dev-network:
    driver: bridge
