version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: rmsa-backend
    env_file:
      - compose.env
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=http://localhost:3000
      - AWS_REGION=${AWS_REGION}
      - AWS_PROFILE=${AWS_PROFILE}
    ports:
      - "3001:3001"
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  frontend:
    build:
      context: ./frontend
    container_name: rmsa-frontend
    env_file:
      - compose.env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3000:3000"



