$env:DATABASE_URL = "mysql://dung:tiendungpro123@cdr.cc3cumaiaj7q.us-east-1.rds.amazonaws.com:3306/resident_management"
$env:JWT_SECRET = "your-super-secret-jwt-key-here"
$env:PORT = "3001"
$env:NODE_ENV = "production"
$env:FRONTEND_URL = "http://localhost:3000"
$env:NEXT_PUBLIC_API_URL = "http://localhost:3001"
$env:AWS_REGION = "us-east-1"
$env:AWS_PROFILE = "Dung"