apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: resident-management
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: ecr-creds
      containers:
      - name: backend
        image: 024190746294.dkr.ecr.us-east-1.amazonaws.com/resident-backend:v3
        imagePullPolicy: Always
        command: ["node", "dist/main.js"]
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: resident-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: resident-config
              key: PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: resident-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: resident-config
              key: JWT_EXPIRES_IN
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: resident-secrets
              key: DATABASE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: resident-management
spec:
  selector:
    app: backend
  ports:
    - port: 3001
      targetPort: 3001
  type: LoadBalancer
