apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: resident-management
data:
  grafana.ini: |
    [server]
    root_url = http://grafana.local/
    
    [security]
    admin_user = admin
    admin_password = admin123
    
    [users]
    allow_sign_up = false
    
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
    
    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/home.json
